name = "weekflow"
account_id = "657ef9c8a4d956832aa095cb76db5fc0"
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]
main = ".output/server/index.mjs"
routes = [{ pattern = "weekflow.pp.ua", custom_domain = true }]

[assets]
directory = ".output/public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "weekflow-db"
database_id = "11c8b63e-ef47-42b7-b667-b70b7e6edd64"
migrations_dir = "server/db/migrations"
